---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true
  require_chef_omnibus: 13.5.3

verifier:
  name: inspec

platforms:
  - name: windows10pro
    driver:
      box: hieunb/windows10pro
      communication: winrm

suites:
  - name: default
    run_list:
      - recipe[test::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
  - name: chocolatey
    run_list:
      - recipe[test::chocolatey]
    verifier:
      inspec_tests:
        - test/smoke/chocolatey
    attributes:
  - name: package
    run_list:
      - recipe[test::package]
    verifier:
      inspec_tests:
        - test/smoke/package
    attributes:
